// Generated by CoffeeScript 1.4.0
(function() {

  exports.create = function(pulse_callback, death_callback, bpm) {
    var BeatingHeart;
    if (bpm == null) {
      bpm = 14;
    }
    BeatingHeart = (function() {

      BeatingHeart.prototype.bpm = 14;

      BeatingHeart.prototype.heart = null;

      BeatingHeart.prototype.Death = null;

      BeatingHeart.prototype.Pulse = null;

      function BeatingHeart(pulse, death) {
        this.Pulse = pulse;
        this.Death = death;
        this.bpm = bpm;
        this.StartHeartBeat();
      }

      BeatingHeart.prototype.StartHeartBeat = function() {
        var heart, heartBeat, _this;
        _this = this;
        heartBeat = function() {
          return _this.HeartBeat();
        };
        return heart = setInterval(heartBeat, this.HeartRate);
      };

      BeatingHeart.prototype.StopHeartBeat = function() {
        this.heart = clearInterval(this.heart);
        return this.Death(this);
      };

      BeatingHeart.prototype.HeartBeat = function() {
        if (!this.Pulse()) {
          return this.StopHeartBeat();
        }
      };

      BeatingHeart.prototype.IsAlive = function() {
        return this.heart != null;
      };

      BeatingHeart.prototype.HeartRate = function() {
        return 1000 * 60 / bpm;
      };

      return BeatingHeart;

    })();
    return new BeatingHeart(pulse_callback, death_callback);
  };

}).call(this);
