// Generated by CoffeeScript 1.4.0
(function() {
  var config_path, is_casper, page, parameter, sassaFraz, system;

  page = require('webpage').create();

  system = require('system');

  is_casper = 2 < system.args.length && system.args[0].indexOf("casper" !== false);

  if ((is_casper && system.args.length !== 5) || (!is_casper && system.args.length !== 2)) {
    console.log("\n\nUsage: " + (is_casper ? "casper" : "phantom") + "js frazzle.js /path/to/fraz/file\n\nThe following parameters were passed to phantomjs:\n\n" + (((function() {
      var _i, _len, _ref, _results;
      _ref = system.args;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        parameter = _ref[_i];
        _results.push("\t\t" + parameter + "\n");
      }
      return _results;
    })()).join("")) + "\n\n");
    phantom.exit();
  }

  config_path = system.args[is_casper ? 4 : 1];

  console.log("\n" + config_path);

  sassaFraz = require("./SassaFraz").create(config_path, function(fraz) {
    console.log("All pages processed.");
    fraz.SaveToFiles();
    return phantom.exit();
  });

}).call(this);
