// Generated by CoffeeScript 1.4.0
(function() {
  var hackScan, page, page_list, system;

  page = require('webpage').create();

  system = require('system');

  page_list = ["www.imperialselect.co.za", "www.google.co.za"];

  console.log("Starting...");

  hackScan = require("./HackScan").create(page_list, function(fraz) {
    console.log("All pages processed.");
    return phantom.exit();
  });

}).call(this);
